language: go

go:
- 1.5
- tip

before_script:
- go get golang.org/x/tools/cmd/goimports
- go get golang.org/x/lint/golint

script:
- go test ./...
- go vet ./...
- golint ./... | xargs -r false
- find . -name '*.go' | xargs gofmt -l | xargs -r false
- find . -name '*.go' | xargs goimports -l | xargs -r false
